### PR TITLE
Add gradient effect

### PR DESCRIPTION
**Pull request by Nenrikido**

### CODE REVIEW

**Comment by isik-kaplan** [comment]
It looks amazing, thank you. It is just that, do we need the `display: block;`, also I know this is weird to ask, but can you change it to a class instead of an id, yes I'm weird haha :D

**Comment by Nenrikido** [comment]
Yes we don't need the `display: block;` as it's already in the user agent but i always overwrite the user agent (as it can be different between browsers) i think everything is in display block by default tho so i could remove it, i will change the id to a class anyway ^^

**Comment by isik-kaplan** [comment]
I'll take care of the `display` line, thanks! And again, thanks for the nice gradient haha.

**Comment by Nenrikido** [comment]
No prob ^^

**Pull request merged**
